version: "3.9"
services:
  flask:
    build: .
    command: gunicorn -b http://130.193.54.38/:5000 hello:app --reload
    environment:
      - FLASK_APP=hello.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=True
    ports:
      - "5000:5000"
    volumes:
      - ./:/root